#region Copyright & License Information
/*
 * Copyright (c) The OpenRA Developers and Contributors
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

using System;
using OpenRA.Mods.Common.Activities;
using OpenRA.Mods.Common.Effects;
using OpenRA.Primitives;
using OpenRA.Traits;

namespace OpenRA.Mods.Common.Traits
{
	[Desc("Support power that flies a BallisticMissile actor in from the map edge nearest the owner's",
		"base and detonates it on the target cell. Unlike " + nameof(NukePower) + ", whose NukeLaunch",
		"projectile builds a Z-only spawn-to-target offset and therefore always descends vertically",
		"onto the target (NukeLaunch.cs:73-78), this arrives laterally.")]
	public class MissileStrikePowerInfo : SupportPowerInfo
	{
		[ActorReference(typeof(BallisticMissileInfo))]
		[FieldLoader.Require]
		[Desc("Actor to spawn at the map edge. Must carry the " + nameof(BallisticMissile) + " trait.")]
		public readonly string MissileActor = null;

		[Desc("Height above the terrain at which the missile enters the map.")]
		public readonly WDist SpawnAltitude = new(6144);

		[Desc("Offset applied to the spawn position, before the altitude. X is along the flight",
			"direction (negative pushes the spawn further off-map), Y is lateral, Z is added to " + nameof(SpawnAltitude) + ".")]
		public readonly WVec SpawnOffset = WVec.Zero;

		[Desc("Delay (in ticks) after the order until the missile is added to the world.",
			"The launch sounds play immediately; this is the gap before anything is visible.")]
		public readonly int MissileDelay = 0;

		[Desc("Altitude above the aim point at which the missile detonates. Zero (the default) is a",
			"ground burst, which is what every instance did before this field existed.",
			"",
			"PITFALL, and it is silent: every warhead carries an AirThreshold (Warhead.cs:41-45,",
			"default 128) above which a terrain-affecting warhead stops seeing terrain target types",
			"and is evaluated against `Air` instead. The `Atomic` warhead set answers this by",
			"writing AirThreshold: 10c0 on every damage row and listing Air on its CreateEffect —",
			"so a detonation at 6c256 is fine and one above 10c0 would silently do NOTHING to the",
			"ground, with no error and no lint. Raising this past a weapon's own AirThreshold is",
			"the failure mode to check for first if an airburst stops hurting anything.",
			"",
			"Note this only moves the DETONATION. The beacon, the minimap ping and the reveal",
			"camera stay on the ground aim point below it, which is what the player pointed at.")]
		public readonly WDist DetonationAltitude = WDist.Zero;

		[Desc("Range of cells the camera should reveal around the target cell.")]
		public readonly WDist CameraRange = WDist.Zero;

		[Desc("Can the camera reveal shroud generated by the `" + nameof(CreatesShroud) + "` trait?")]
		public readonly bool RevealGeneratedShroud = false;

		[Desc("Reveal cells to players with these relationships only.")]
		public readonly PlayerRelationship CameraRelationships = PlayerRelationship.Ally;

		[Desc("Amount of time before impact to spawn the camera.")]
		public readonly int CameraSpawnAdvance = 25;

		[Desc("Amount of time after impact to remove the camera.")]
		public readonly int CameraRemoveDelay = 25;

		[Desc("Amount of time before impact to remove the beacon.")]
		public readonly int BeaconRemoveAdvance = 5;

		public override object Create(ActorInitializer init) { return new MissileStrikePower(init.Self, this); }
	}

	public class MissileStrikePower : SupportPower
	{
		readonly MissileStrikePowerInfo info;

		public MissileStrikePower(Actor self, MissileStrikePowerInfo info)
			: base(self, info)
		{
			this.info = info;
		}

		public override void Activate(Actor self, Order order, SupportPowerManager manager)
		{
			base.Activate(self, order, manager);
			PlayLaunchSounds();

			Activate(self, order.Target.CenterPosition);
		}

		public Actor Activate(Actor self, WPos targetPosition)
		{
			var world = self.World;
			var map = world.Map;

			// Same rule as the airstrike: the strike comes in over the player's own back line,
			// not from a bearing the player picks (AirstrikePower.cs:79, established by a20c8a82).
			var spawnCell = map.ChooseClosestEdgeCell(self.Owner.HomeLocation);
			var spawnPos = map.CenterOfCell(spawnCell);

			// Face from the edge toward the target, then apply the offset in that frame so that
			// SpawnOffset.X reads as "further back along the approach".
			var facing = (targetPosition - spawnPos).HorizontalLengthSquared != 0
				? (targetPosition - spawnPos).Yaw
				: WAngle.Zero;

			var offset = info.SpawnOffset;
			if (offset != WVec.Zero)
				spawnPos += new WVec(offset.Y, -offset.X, 0).Rotate(WRot.FromYaw(facing)) + new WVec(0, 0, offset.Z);

			spawnPos += new WVec(0, 0, info.SpawnAltitude.Length);

			var missile = world.CreateActor(false, info.MissileActor, new TypeDictionary
			{
				new CenterPositionInit(spawnPos),
				new OwnerInit(self.Owner),
				new FacingInit(facing),
			});

			// ORDERING IS LOAD-BEARING. BallisticMissile.AddedToWorld queues BallisticMissileFly
			// (BallisticMissile.cs:218), whose constructor reads Target.CenterPosition
			// unconditionally — so an unset Target throws the InvalidOperationException documented
			// at MissileSpawnerMaster.cs:85-87. CreateActor(false, ...) builds the actor without
			// adding it, the add happens below, and the assignment goes in between: exactly the
			// handshake MissileSpawnerMaster.cs:112,116 performs.
			var bm = missile.Trait<BallisticMissile>();

			// The missile flies to the DETONATION point, not to the aim point. BallisticMissileFly
			// takes its whole trajectory from Target.CenterPosition (BallisticMissileFly.cs:45),
			// terminates with SetPosition(self, targetPos) and only then queues the kill
			// (BallisticMissileFly.cs:216-221) — so the actor really is sitting at this position
			// when Explodes fires the payload at self.CenterPosition (Explodes.cs:133). Nothing
			// downstream needs telling: CreateEffectWarhead spawns its sprite at the impact
			// position unless ForceDisplayAtGroundLevel is set (CreateEffectWarhead.cs:140-150),
			// so the explosion animation follows the burst height on its own.
			bm.Target = Target.FromPos(targetPosition + new WVec(0, 0, info.DetonationAltitude.Length));

			// At MissileDelay 0 this is byte-for-byte MissileSpawnerMaster's own add
			// (BaseSpawnerMaster.cs:228-250). SpawnActorEffect is only reached when a delay is
			// asked for; it holds the already-created actor and adds it N ticks later, which is the
			// only deferred-add form in the codebase that preserves the Target-before-Add ordering.
			if (info.MissileDelay <= 0)
				world.AddFrameEndTask(w => w.Add(missile));
			else
				world.AddFrameEndTask(w => w.Add(new SpawnActorEffect(missile, info.MissileDelay)));

			// Ticks from the order to the detonation. BallisticMissileFly.EstimateArcTicks is the
			// activity's own arithmetic, so this is the flight the missile will actually fly rather
			// than a second number that has to be kept in step by hand.
			var hDist = (targetPosition - spawnPos).HorizontalLength;
			var impactDelay = info.MissileDelay + bm.Info.PreLaunchTicks
				+ BallisticMissileFly.EstimateArcTicks(bm.Info, hDist);

			if (info.CameraRange != WDist.Zero)
			{
				var type = info.RevealGeneratedShroud ? MapLayers.Type.Vision : MapLayers.Type.PassiveVisibility;
				var cameraDelay = Math.Max(0, impactDelay - info.CameraSpawnAdvance);

				world.AddFrameEndTask(w => w.Add(new RevealShroudEffect(targetPosition, info.CameraRange, type,
					self.Owner, info.CameraRelationships, cameraDelay, info.CameraSpawnAdvance + info.CameraRemoveDelay)));
			}

			if (Info.DisplayBeacon)
			{
				// The clock is driven off the missile's LIVE POSITION once it is flying, the way the
				// airstrike beacon is (AirstrikePower.cs:168-170), so it stays honest if the flight
				// overruns the estimate above.
				//
				// It cannot be position-driven before that, and MissileDelay is what makes this
				// matter: for those ticks the actor exists but is not in the world, sitting at its
				// spawn position, so the position formula reads a constant 0 and the beacon shows a
				// clock frozen at the top of its sweep for the whole wait — which reads to the
				// player as "the order did not take". Ticks are the only clock available then, and
				// they are exact during the wait for the same reason the flight is not: nothing can
				// make SpawnActorEffect take longer than the count it was handed.
				var orderTick = world.WorldTick;
				var delayFraction = impactDelay > 0
					? Math.Clamp(info.MissileDelay * 1f / impactDelay, 0f, 1f)
					: 0f;

				float FractionComplete()
				{
					if (missile.IsDead || missile.Disposed)
						return 1f;

					if (!missile.IsInWorld)
						return impactDelay > 0
							? Math.Clamp((world.WorldTick - orderTick) * 1f / impactDelay, 0f, 1f)
							: 1f;

					var flown = hDist <= 0
						? 1f
						: 1f - ((missile.CenterPosition - targetPosition).HorizontalLength * 1f / hDist);

					return delayFraction + (Math.Clamp(flown, 0f, 1f) * (1f - delayFraction));
				}

				var beacon = new Beacon(
					self.Owner,
					targetPosition,
					Info.BeaconPaletteIsPlayerPalette,
					Info.BeaconPalette,
					Info.BeaconImage,
					Info.BeaconPoster,
					Info.BeaconPosterPalette,
					Info.BeaconSequence,
					Info.ArrowSequence,
					Info.CircleSequence,
					Info.ClockSequence,
					FractionComplete,
					Info.BeaconDelay,
					Math.Max(1, impactDelay - info.BeaconRemoveAdvance));

				world.AddFrameEndTask(w => w.Add(beacon));
			}

			return missile;
		}
	}
}
