; Copyright (c) The OpenRA Developers and Contributors
; This file is part of OpenRA.
;
;  OpenRA is free software: you can redistribute it and/or modify
;  it under the terms of the GNU General Public License as published by
;  the Free Software Foundation, either version 3 of the License, or
;  (at your option) any later version.
;
;  OpenRA is distributed in the hope that it will be useful,
;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;  GNU General Public License for more details.
;
;  You should have received a copy of the GNU General Public License
;  along with OpenRA.  If not, see <http://www.gnu.org/licenses/>.


!include "MUI2.nsh"
!include "FileFunc.nsh"
!include "WordFunc.nsh"

; Generated by packaging/windows/gen-uninstall-manifest.py and passed in by
; buildpackage.sh. Without it the uninstaller would have nothing to delete, so
; fail the build loudly rather than emit an installer that cannot uninstall.
!ifndef UNINSTALL_MANIFEST
	!error "UNINSTALL_MANIFEST is not defined. Run this through packaging/windows/buildpackage.sh, which generates the manifest and passes -DUNINSTALL_MANIFEST=<path>."
!endif

Name "${PACKAGING_DISPLAY_NAME}"
OutFile "${OUTFILE}"

ManifestDPIAware true

Unicode True

Function .onInit
	!ifndef USE_PROGRAMFILES32
		SetRegView 64
	!endif
	ReadRegStr $INSTDIR HKLM "Software\${PACKAGING_WINDOWS_REGISTRY_KEY}" "InstallDir"
	StrCmp $INSTDIR "" unset 0

	; A previous install wrote that value, and before the guards below existed it
	; could have been anything the user accepted -- their Desktop, for one
	; (2026-09-08). One bad install must not poison the default of the next one,
	; so the remembered path is held to the same rule as a typed one.
	Push $INSTDIR
	Call IsUnsafeInstDir
	Pop $R0
	StrCmp $R0 "1" unset done

	unset:
	!ifndef USE_PROGRAMFILES32
		StrCpy $INSTDIR "$PROGRAMFILES64\${PACKAGING_WINDOWS_INSTALL_DIR_NAME}"
	!else
		StrCpy $INSTDIR "$PROGRAMFILES32\${PACKAGING_WINDOWS_INSTALL_DIR_NAME}"
	!endif
	done:
FunctionEnd

SetCompressor lzma
RequestExecutionLevel admin

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_LICENSE "${PACKAGING_WINDOWS_LICENSE_FILE}"

; The directory page's Next button greys out for a rejected path (see
; .onVerifyInstDir) and there is no way to explain that from inside the
; callback -- it fires on every keystroke, so a message box there would spam.
; State the rule up front instead, where it is always on screen.
!define MUI_DIRECTORYPAGE_TEXT_TOP "Setup will install ${PACKAGING_DISPLAY_NAME} in the following folder. To install in a different folder, click Browse and select another one.$\r$\n$\r$\nUninstalling removes this game's files from that folder, so it must be a folder of its own: your Desktop, Documents, user profile folder and the root of a drive are not accepted. If the folder you pick already contains other files, a subfolder will be created inside it."
!define MUI_PAGE_CUSTOMFUNCTION_LEAVE DirectoryPageLeave
!insertmacro MUI_PAGE_DIRECTORY

!define MUI_STARTMENUPAGE_REGISTRY_ROOT "HKLM"
!define MUI_STARTMENUPAGE_REGISTRY_KEY "Software\${PACKAGING_WINDOWS_REGISTRY_KEY}"
!define MUI_STARTMENUPAGE_REGISTRY_VALUENAME "Start Menu Folder"
!define MUI_STARTMENUPAGE_DEFAULTFOLDER "OpenRA"

Var StartMenuFolder
!insertmacro MUI_PAGE_STARTMENU Application $StartMenuFolder

!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_INSTFILES

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_UNPAGE_FINISH

!insertmacro MUI_LANGUAGE "English"

;***************************
;Install directory safety
;***************************
; The uninstaller -- and .onInstFailed -- delete inside $INSTDIR. On 2026-09-08
; a user accepted their Desktop as $INSTDIR and the pair of behaviours that
; follows from that was close to unrecoverable. Two guards, deliberately split:
;
;   IsUnsafeInstDir / .onVerifyInstDir  refuses a path that is somebody's
;                                       document store rather than a program
;                                       folder. Cannot be overridden.
;   DirectoryPageLeave                  accepts the path but moves the install
;                                       into a subfolder of it when it already
;                                       holds other files.
;
; The append has to live in the page's LEAVE callback, not in .onVerifyInstDir:
; that one is called on every keystroke in the directory field, so writing to
; $INSTDIR there appends once per character typed.

; Push a path, call, pop "1" when that path must never be used as $INSTDIR.
Function IsUnsafeInstDir
	Exch $R0
	Push $R1
	Push $R2
	Push $R3

	StrCmp $R0 "" unsafe

	; Normalise away a single trailing backslash, so "C:\" and "C:" -- and
	; "$DESKTOP\" and "$DESKTOP" -- compare alike.
	StrCpy $R1 $R0 1 -1
	StrCmp $R1 "\" 0 nostrip
		StrCpy $R0 $R0 -1
	nostrip:

	; Shorter than "C:\x" is a drive root ("C:\" normalises to "C:") or nonsense.
	StrLen $R1 $R0
	IntCmp $R1 3 0 unsafe 0

	; A UNC share root, \\server\share, is the network equivalent of a drive
	; root: count the separators below the leading pair and require at least the
	; two that \\server\share\folder has.
	StrCpy $R2 $R0 2
	StrCmp $R2 "\\" 0 notunc
		StrCpy $R3 0
		StrCpy $R1 2
		uncloop:
			StrCpy $R2 $R0 1 $R1
			StrCmp $R2 "" uncdone
			StrCmp $R2 "\" 0 uncnext
				IntOp $R3 $R3 + 1
			uncnext:
			IntOp $R1 $R1 + 1
			Goto uncloop
		uncdone:
		IntCmp $R3 2 notunc unsafe notunc
	notunc:

	; Well-known folders. StrCmp is case-insensitive. These are checked in both
	; shell-var contexts because the installer elevates: "current" may resolve to
	; the elevating administrator rather than the person at the keyboard.
	SetShellVarContext current
	StrCmp $R0 "$DESKTOP" unsafe
	StrCmp $R0 "$DOCUMENTS" unsafe
	StrCmp $R0 "$PROFILE" unsafe
	StrCmp $R0 "$APPDATA" unsafe
	StrCmp $R0 "$LOCALAPPDATA" unsafe
	StrCmp $R0 "$MUSIC" unsafe
	StrCmp $R0 "$PICTURES" unsafe
	StrCmp $R0 "$VIDEOS" unsafe
	StrCmp $R0 "$TEMP" unsafe
	StrCmp $R0 "$WINDIR" unsafe
	StrCmp $R0 "$SYSDIR" unsafe
	StrCmp $R0 "$PROGRAMFILES" unsafe
	StrCmp $R0 "$PROGRAMFILES32" unsafe
	StrCmp $R0 "$PROGRAMFILES64" unsafe
	StrCmp $R0 "$COMMONFILES" unsafe
	StrCmp $R0 "$STARTMENU" unsafe
	StrCmp $R0 "$SMPROGRAMS" unsafe

	SetShellVarContext all
	StrCmp $R0 "$DESKTOP" unsafe
	StrCmp $R0 "$DOCUMENTS" unsafe
	StrCmp $R0 "$APPDATA" unsafe
	StrCmp $R0 "$STARTMENU" unsafe
	StrCmp $R0 "$SMPROGRAMS" unsafe
	SetShellVarContext current

	; The constants above follow shell redirection (OneDrive moves $DESKTOP), so
	; also name the literal profile folders, which keep their contents and keep
	; existing after a redirect. NSIS has no $DOWNLOADS constant at all.
	StrCmp $R0 "$PROFILE\Desktop" unsafe
	StrCmp $R0 "$PROFILE\Documents" unsafe
	StrCmp $R0 "$PROFILE\Downloads" unsafe
	StrCmp $R0 "$PROFILE\OneDrive" unsafe

	StrCpy $R0 "0"
	Goto done

	unsafe:
	SetShellVarContext current
	StrCpy $R0 "1"

	done:
	Pop $R3
	Pop $R2
	Pop $R1
	Exch $R0
FunctionEnd

Function .onVerifyInstDir
	Push $R0
	Push $INSTDIR
	Call IsUnsafeInstDir
	Pop $R0
	StrCmp $R0 "1" 0 ok
		Pop $R0
		Abort
	ok:
	Pop $R0
FunctionEnd

Function DirectoryPageLeave
	Push $R0
	Push $0
	Push $1

	; Reinstalling over ourselves stays put -- the uninstaller and the registry
	; both point at this path already.
	IfFileExists "$INSTDIR\${PACKAGING_WINDOWS_LAUNCHER_NAME}.exe" keep
	IfFileExists "$INSTDIR\uninstaller.exe" keep

	; ${DirState} is FindFirst plus at most two FindNext -- it does not walk the
	; tree. -1 missing, 0 empty, 1 has contents.
	${DirState} "$INSTDIR" $R0
	StrCmp $R0 "1" 0 keep
		StrCpy $INSTDIR "$INSTDIR\${PACKAGING_WINDOWS_INSTALL_DIR_NAME}"
		MessageBox MB_OK|MB_ICONINFORMATION "The folder you chose already contains other files.$\r$\n$\r$\nUninstalling ${PACKAGING_DISPLAY_NAME} removes its files from wherever it was installed, so it will be installed into its own subfolder instead:$\r$\n$\r$\n$INSTDIR"

	keep:
	Pop $1
	Pop $0
	Pop $R0
FunctionEnd

;***************************
;Section Definitions
;***************************
Section "-Reg" Reg

	; Installation directory
	WriteRegStr HKLM "Software\${PACKAGING_WINDOWS_REGISTRY_KEY}" "InstallDir" $INSTDIR

	; Join server URL Scheme
	WriteRegStr HKLM "Software\Classes\openra-${MOD_ID}-${TAG}" "" "URL:Join OpenRA server"
	WriteRegStr HKLM "Software\Classes\openra-${MOD_ID}-${TAG}" "URL Protocol" ""
	WriteRegStr HKLM "Software\Classes\openra-${MOD_ID}-${TAG}\DefaultIcon" "" "$INSTDIR\${MOD_ID}.ico,0"
	WriteRegStr HKLM "Software\Classes\openra-${MOD_ID}-${TAG}\Shell\Open\Command" "" "$INSTDIR\${PACKAGING_WINDOWS_LAUNCHER_NAME}.exe Launch.URI=%1"

	!ifdef USE_DISCORDID
		WriteRegStr HKLM "Software\Classes\discord-${USE_DISCORDID}" "" "URL:Run game ${USE_DISCORDID} protocol"
		WriteRegStr HKLM "Software\Classes\discord-${USE_DISCORDID}" "URL Protocol" ""
		WriteRegStr HKLM "Software\Classes\discord-${USE_DISCORDID}\DefaultIcon" "" "$INSTDIR\${MOD_ID}.ico,0"
		WriteRegStr HKLM "Software\Classes\discord-${USE_DISCORDID}\Shell\Open\Command" "" "$INSTDIR\${PACKAGING_WINDOWS_LAUNCHER_NAME}.exe"
	!endif

SectionEnd

Section "Game" GAME
	SectionIn RO

	SetOutPath "$INSTDIR"
	File "${SRCDIR}\*.exe"
	File "${SRCDIR}\*.dll.config"
	File "${SRCDIR}\*.dll"
	File "${SRCDIR}\*.ico"
	File "${SRCDIR}\*.deps.json"
	File "${SRCDIR}\*.runtimeconfig.json"
	File "${SRCDIR}\global mix database.dat"
	File "${SRCDIR}\IP2LOCATION-LITE-DB1.IPV6.BIN.ZIP"
	File "${SRCDIR}\VERSION"
	File "${SRCDIR}\AUTHORS"
	File "${SRCDIR}\COPYING"
	File "${SRCDIR}\SOURCE-OFFER.txt"
	File /r "${SRCDIR}\mods"

	!insertmacro MUI_STARTMENU_WRITE_BEGIN Application
		CreateDirectory "$SMPROGRAMS\$StartMenuFolder"
		CreateShortCut "$SMPROGRAMS\$StartMenuFolder\${PACKAGING_DISPLAY_NAME}.lnk" "$OUTDIR\${PACKAGING_WINDOWS_LAUNCHER_NAME}.exe" "" \
			"$OUTDIR\${PACKAGING_WINDOWS_LAUNCHER_NAME}.exe" "" "" "" ""
	!insertmacro MUI_STARTMENU_WRITE_END

	SetOutPath "$INSTDIR\lua"
	File "${SRCDIR}\lua\*.lua"

	SetOutPath "$INSTDIR\glsl"
	File "${SRCDIR}\glsl\*.frag"
	File "${SRCDIR}\glsl\*.vert"

	; Estimated install size for the control panel properties.
	;
	; This used to be `${GetSize} "$INSTDIR" "/S=0K"`, which recursively walks
	; $INSTDIR at install time. On 2026-09-08, with a Desktop holding a repo
	; checkout as $INSTDIR, that walk was 275,720 files / 71 GB: ~25 minutes
	; with no progress and no cancel. The size is a property of the build, not
	; of the destination, so it is measured once at build time instead --
	; gen-uninstall-manifest.py prints it while it is already walking the tree.
	!ifdef INSTALL_SIZE_KB
		WriteRegDWORD HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "EstimatedSize" ${INSTALL_SIZE_KB}
	!endif

	SetShellVarContext all
	CreateDirectory "$APPDATA\OpenRA\ModMetadata"
	SetOutPath "$INSTDIR"
	nsExec::ExecToLog '"$INSTDIR\OpenRA.Utility.exe" ${MOD_ID} --register-mod "$INSTDIR\${PACKAGING_WINDOWS_LAUNCHER_NAME}.exe" system'
	nsExec::ExecToLog '"$INSTDIR\OpenRA.Utility.exe" ${MOD_ID} --clear-invalid-mod-registrations system'
	SetShellVarContext current

SectionEnd

Section "Desktop Shortcut" DESKTOPSHORTCUT
	SetOutPath "$INSTDIR"
	CreateShortCut "$DESKTOP\OpenRA - ${PACKAGING_DISPLAY_NAME}.lnk" "$INSTDIR\${PACKAGING_WINDOWS_LAUNCHER_NAME}.exe" "" \
		"$INSTDIR\${PACKAGING_WINDOWS_LAUNCHER_NAME}.exe" "" "" "" ""
SectionEnd

;***************************
;Uninstaller Sections
;***************************
Section "-Uninstaller"
	WriteUninstaller $INSTDIR\uninstaller.exe
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "DisplayName" "${PACKAGING_DISPLAY_NAME}"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "UninstallString" "$INSTDIR\uninstaller.exe"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "QuietUninstallString" "$\"$INSTDIR\uninstall.exe$\" /S"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "InstallLocation" "$INSTDIR"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "DisplayIcon" "$INSTDIR\${MOD_ID}.ico"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "Publisher" "${PACKAGING_AUTHORS}"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "URLInfoAbout" "${PACKAGING_WEBSITE_URL}"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "DisplayVersion" "${TAG}"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "NoModify" "1"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}" "NoRepair" "1"
SectionEnd

!macro Clean UN
Function ${UN}Clean
	nsExec::ExecToLog '"$INSTDIR\OpenRA.Utility.exe" ${MOD_ID} --unregister-mod system'

	; Delete exactly the names this build installed, and nothing else.
	;
	; This used to be `Delete $INSTDIR\*.exe`, `*.dll`, `*.ico` plus `RMDir /r`
	; over mods, maps, glsl, lua and Support. Against the Desktop that a user
	; accepted as $INSTDIR on 2026-09-08 it would have taken their Firefox.exe
	; and every other unrelated binary, icon and same-named folder there.
	;
	; ${UNINSTALL_MANIFEST} is generated from the built tree at build time by
	; packaging/windows/gen-uninstall-manifest.py: one `Delete` per file, then
	; one `RMDir` per directory deepest-first. `RMDir` without /r only removes
	; an empty directory, so anything the user put inside one of ours keeps both
	; itself and its directory.
	;
	; $INSTDIR\Support and $INSTDIR\maps are deliberately NOT in the manifest
	; and are no longer removed: the installer never creates them, and in a
	; portable install they are the player's settings, replays, saves and
	; downloaded maps.
	Delete "$INSTDIR\uninstaller.exe"
	!include "${UNINSTALL_MANIFEST}"

	!ifndef USE_PROGRAMFILES32
		SetRegView 64
	!endif

	DeleteRegKey HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PACKAGING_WINDOWS_REGISTRY_KEY}"
	DeleteRegKey HKLM "Software\Classes\openra-${MOD_ID}-${TAG}"

	!ifdef USE_DISCORDID
		DeleteRegKey HKLM "Software\Classes\discord-${USE_DISCORDID}"
	!endif

	; Non-recursive: $INSTDIR survives if anything at all is left in it.
	RMDir $INSTDIR

	!insertmacro MUI_STARTMENU_GETFOLDER Application $StartMenuFolder

	; Clean up start menu: Delete all our icons, and the OpenRA folder
	; *only* if we were the only installed version
	Delete "$SMPROGRAMS\$StartMenuFolder\${PACKAGING_DISPLAY_NAME}.lnk"
	RMDir "$SMPROGRAMS\$StartMenuFolder"

	Delete "$DESKTOP\OpenRA - ${PACKAGING_DISPLAY_NAME}.lnk"
	DeleteRegKey HKLM "Software\${PACKAGING_WINDOWS_REGISTRY_KEY}"
FunctionEnd
!macroend

!insertmacro Clean ""
!insertmacro Clean "un."

Section "Uninstall"
	Call un.Clean
SectionEnd

;***************************
;Section Descriptions
;***************************
LangString DESC_GAME ${LANG_ENGLISH} "${PACKAGING_DISPLAY_NAME} game files."
LangString DESC_DESKTOPSHORTCUT ${LANG_ENGLISH} "Place shortcut on the Desktop."

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
	!insertmacro MUI_DESCRIPTION_TEXT ${GAME} $(DESC_GAME)
	!insertmacro MUI_DESCRIPTION_TEXT ${DESKTOPSHORTCUT} $(DESC_DESKTOPSHORTCUT)
!insertmacro MUI_FUNCTION_DESCRIPTION_END

;***************************
;Callbacks
;***************************

Function .onInstFailed
	Call Clean
FunctionEnd
