#!/usr/bin/env python3
# Copyright (c) The OpenRA Developers and Contributors
# This file is part of OpenRA, which is free software. It is made
# available to you under the terms of the GNU General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version. For more
# information, see COPYING.
r"""Emit the NSIS uninstall manifest for the Windows installer.

WHY THIS EXISTS
---------------
buildpackage.nsi used to uninstall by wildcard -- `Delete $INSTDIR\*.exe`,
`*.dll`, `*.ico` plus `RMDir /r` over mods/maps/glsl/lua/Support. On
2026-09-08 a user accepted their Desktop as $INSTDIR; that uninstaller
would have deleted every unrelated .exe/.dll/.ico sitting on the Desktop
(Firefox.exe among them) and recursively removed any folder carrying one
of those five names. This script replaces the wildcards with an explicit
list of the exact names the build produced, so the uninstaller can only
ever remove files the installer could have written.

WHAT IT EMITS
-------------
An NSIS fragment, `!include`d inside buildpackage.nsi's `Clean` macro:

    Delete "$INSTDIR\<relative path>"   -- one per file, shallowest first
    RMDir  "$INSTDIR\<relative path>"   -- one per directory, DEEPEST first

`RMDir` without /r only removes a directory once it is empty, so a
directory that still holds user files survives, as does everything in it.
The list covers only the directories this build created; $INSTDIR\Support
and $INSTDIR\maps -- user settings, replays, saves and downloaded maps in
a portable install -- are deliberately absent, where the wildcard version
took both with `RMDir /r`.

The manifest is derived from the whole built tree, which is a superset of
what the `File` lines in Section "Game" install (those take named
extensions only). A superset is the safe direction: every extra entry is
a filename this build produced, so the worst case is removing a stale
file from an older install. It is also exactly the set the portable .zip
ships, which is the set the 2026-09-08 manual cleanup was verified
against by CRC32.

USAGE
    gen-uninstall-manifest.py <builtdir> <outfile>
Writes <outfile>; prints the install size in KB on stdout, for the
installer's Add/Remove Programs "EstimatedSize" value.
"""

import os
import sys

BACKSLASH = chr(92)


def nsis_escape(path):
    """$ is NSIS's variable sigil; $$ is a literal dollar sign."""
    return path.replace('$', '$$')


def main():
    if len(sys.argv) != 3:
        sys.stderr.write('Usage: %s <builtdir> <outfile>\n' % os.path.basename(sys.argv[0]))
        return 1

    srcdir, outfile = sys.argv[1], sys.argv[2]
    if not os.path.isdir(srcdir):
        sys.stderr.write('gen-uninstall-manifest: not a directory: %s\n' % srcdir)
        return 1

    files = []
    dirs = []
    total_bytes = 0

    for root, dirnames, filenames in os.walk(srcdir):
        dirnames.sort()
        filenames.sort()
        rel = os.path.relpath(root, srcdir)
        if rel != '.':
            dirs.append(rel.replace(os.sep, BACKSLASH))
        for name in filenames:
            full = os.path.join(root, name)
            if os.path.islink(full):
                # The build resolves symlinks as it copies (cp -Lr); one surviving
                # here means a broken tree, not a file to ship.
                sys.stderr.write('gen-uninstall-manifest: unexpected symlink: %s\n' % full)
                return 1
            total_bytes += os.path.getsize(full)
            relfile = name if rel == '.' else os.path.join(rel, name)
            files.append(relfile.replace(os.sep, BACKSLASH))

    if not files:
        sys.stderr.write('gen-uninstall-manifest: %s is empty -- refusing to write an empty '
                         'manifest, which would leave an uninstaller that removes nothing.\n'
                         % srcdir)
        return 1

    # Deepest first, so a parent is only attempted once its children are gone.
    dirs.sort(key=lambda d: (-d.count(BACKSLASH), d))

    with open(outfile, 'w', encoding='utf-8', newline='\r\n') as out:
        out.write('; GENERATED by packaging/windows/gen-uninstall-manifest.py -- DO NOT EDIT.\n')
        out.write('; Source tree: %s\n' % srcdir)
        out.write('; %d files, %d directories, %d bytes.\n' % (len(files), len(dirs), total_bytes))
        out.write(';\n')
        out.write('; Included twice (installer rollback + uninstaller) from the Clean macro,\n')
        out.write('; so it carries instructions only -- a !define here would collide on the\n')
        out.write('; second inclusion.\n\n')
        for f in files:
            out.write('\tDelete "$INSTDIR%s%s"\n' % (BACKSLASH, nsis_escape(f)))
        out.write('\n')
        for d in dirs:
            out.write('\tRMDir "$INSTDIR%s%s"\n' % (BACKSLASH, nsis_escape(d)))

    # NSIS EstimatedSize is a DWORD of KB.
    sys.stdout.write('%d\n' % ((total_bytes + 1023) // 1024))
    return 0


if __name__ == '__main__':
    sys.exit(main())
