#region Copyright & License Information
/*
 * Copyright (c) The OpenRA Developers and Contributors
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using OpenRA.Traits;

namespace OpenRA
{
	/// <summary>
	/// A content-addressed store for generated shadow/density layers, living in the support dir
	/// rather than inside the map package.
	///
	/// <para>It must not live in the package: Map.ComputeUID hashes every .bin in the package, so
	/// writing a generated shadows.bin back into the map would change that map's own UID underneath
	/// a live lobby and diverge the generating player from everyone else.</para>
	///
	/// <para>Every failure mode here is a MISS, never an exception. The caller's fallback is
	/// in-memory generation, which always produces a correct layer; refusing to play, or playing
	/// with an absent layer, would be a guaranteed desync because shadow feeds vision attenuation
	/// and firing LOS (see MapShadowLayer's class comment).</para>
	/// </summary>
	public static class ShadowCache
	{
		/// <summary>
		/// Bump this whenever the generated bytes change for unchanged map content — the shadow
		/// curve in Map.RecomputeShadowFrom (ForestGroundShadow, the airborne /5f, the obstacle
		/// height, the annulus range), or the serialization order in Map.SaveShadowsBinaryData.
		///
		/// <para>This const is what makes editing the curve safe. Without it a cached entry keeps
		/// the old concealment values forever while a freshly-generated one uses the new ones, so
		/// two players disagree about what can see and shoot what. It is also what lets an old
		/// replay regenerate the same bytes it was recorded against.</para>
		/// </summary>
		public const int AlgoVersion = 1;

		const uint Magic = 0x57335348; // "W3SH"
		const int HeaderVersion = 1;

		const string TempSuffix = ".tmp";
		static readonly TimeSpan StaleTempAge = TimeSpan.FromHours(1);

		/// <summary>
		/// Cap on total bytes under the cache directory.
		///
		/// <para>The ten shipped maps come to roughly 461 MB, but that is NOT the working set: each
		/// autotest scenario carries its own map.yaml, so it mints its own uid and its own entry even
		/// where the terrain is identical. Playing everything plus running the autotest suite is
		/// about 19 entries and roughly 750 MB. 1 GiB clears that, but by ~25% rather than by the
		/// 2x an entry-per-shipped-map reading would suggest. The case the cap exists for is a mapper
		/// iterating in the editor: every save changes the map UID and therefore mints a new entry,
		/// at up to 87 MB for the largest map, and nothing else would ever reclaim them. From a full
		/// 750 MB working set 1 GiB gives such a mapper only about three saves before it starts
		/// reclaiming their own stale entries, oldest-used first.</para>
		/// </summary>
		public const long MaxCacheBytes = 1024L * 1024 * 1024;

		// Entries being read right now, so eviction cannot delete a file out from under a reader in
		// this process. Cross-process, deleting an open file is harmless on Unix (the reader keeps
		// its fd) and fails with IOException on Windows, which Evict catches and skips.
		static readonly HashSet<string> InUse = new HashSet<string>();
		static readonly object SyncRoot = new object();

		public static string CacheDir => Path.Combine(Platform.SupportDir, "Cache", "shadows");

		/// <summary>
		/// SHA1(mapUid || densityRulesHash || AlgoVersion). Each term closes one staleness route:
		/// mapUid covers every terrain, actor, lua and png edit; densityRulesHash covers a rules-only
		/// edit that changes density with the map bytes untouched; AlgoVersion covers a change to the
		/// generator itself.
		/// </summary>
		public static string ComputeKey(string mapUid, string densityRulesHash)
		{
			return ComputeKey(mapUid, densityRulesHash, AlgoVersion);
		}

		/// <summary>As <see cref="ComputeKey(string, string)"/>, with the algorithm version supplied
		/// explicitly so a test can show that bumping it does change the key.</summary>
		public static string ComputeKey(string mapUid, string densityRulesHash, int algoVersion)
		{
			return CryptoUtil.SHA1Hash(
				$"{mapUid}|{densityRulesHash}|{algoVersion.ToString(CultureInfo.InvariantCulture)}");
		}

		/// <summary>
		/// Hash every value that SetDensityLayer would read out of the rules, so a balance edit to a
		/// building's density invalidates the cache even though no map byte changed.
		/// </summary>
		public static string ComputeDensityRulesHash(Ruleset rules)
		{
			var sb = new StringBuilder();

			// Ordered by actor name so the hash does not depend on dictionary enumeration order.
			foreach (var actor in rules.Actors.OrderBy(kv => kv.Key, StringComparer.Ordinal))
			{
				var density = actor.Value.TraitInfoOrDefault<IDensityInfo>();
				if (density == null)
					continue;

				sb.Append(actor.Key);
				foreach (var d in density.Density().OrderBy(kv => kv.Key.X).ThenBy(kv => kv.Key.Y))
					sb.Append(FormattableString.Invariant($":{d.Key.X},{d.Key.Y}={d.Value}"));

				sb.Append(';');
			}

			return CryptoUtil.SHA1Hash(sb.ToString());
		}

		/// <summary>
		/// Probe the cache and hand a validated payload stream to <paramref name="read"/>.
		/// Returns false — never throws — for a missing, truncated, corrupt or foreign entry.
		/// </summary>
		public static bool TryLoad(string key, Action<Stream> read)
		{
			return TryLoad(CacheDir, key, read);
		}

		/// <summary>As <see cref="TryLoad(string, Action{Stream})"/>, against an explicit cache root.</summary>
		public static bool TryLoad(string dir, string key, Action<Stream> read)
		{
			var path = PathForKey(dir, key);

			lock (SyncRoot)
				InUse.Add(key);

			try
			{
				using (var file = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read))
				{
					var payloadLength = ReadAndValidateHeader(file, key);
					if (payloadLength < 0)
						return false;

					if (file.Length - file.Position != payloadLength)
						return false;

					var payloadStart = file.Position;
					read(file);

					// The reader must consume the payload exactly. A SHORT read is the dangerous case
					// and the length check above cannot catch it: if the annulus geometry shrinks, the
					// reader stops early and the leading bytes are accepted as a whole layer. That is
					// reachable with uid, rules and AlgoVersion all unchanged — a mod-level MapGrid
					// change alters the pair count and is in no key term.
					if (file.Position - payloadStart != payloadLength)
						return false;
				}

				// LRU stamp. Deliberately last-write-time rather than last-access-time: atime is
				// disabled or coarsened on many filesystems, so it cannot order eviction reliably.
				try { File.SetLastWriteTimeUtc(path, DateTime.UtcNow); }
				catch (Exception) { }

				return true;
			}
			catch (Exception e)
			{
				LogDiagnostic($"Shadow cache miss for {key}: {e.Message}");
				return false;
			}
			finally
			{
				lock (SyncRoot)
					InUse.Remove(key);
			}
		}

		/// <summary>
		/// Write an entry, evicting first if needed. A failure here costs only the next load's
		/// generation time, so it is logged and swallowed.
		/// </summary>
		public static void TrySave(string key, byte[] payload)
		{
			TrySave(CacheDir, key, payload, MaxCacheBytes);
		}

		/// <summary>As <see cref="TrySave(string, byte[])"/>, against an explicit cache root and cap.</summary>
		public static void TrySave(string dir, string key, byte[] payload, long maxBytes)
		{
			// Declared out here so the catch can reclaim it. Flush(true) below is the most likely
			// call in this method to throw, because a deferred ENOSPC surfaces at fsync rather than
			// at write — and by then the temp is already on disk at full size. Leaving it would
			// strand up to 87 MB that the reaper only revisits on the next TrySave, which on a full
			// disk fails the same way, and which the *.bin cap accounting cannot see.
			string temp = null;

			try
			{
				// An entry bigger than the whole cap can never fit, and evicting for it would clear
				// every other entry and then store it anyway, leaving the directory over cap with
				// nothing else left in it. Refuse instead; the only cost is regenerating this one map
				// next load. Unreachable today at 87 MB against 1 GiB, but MaxCacheBytes is public and
				// a smaller cap would hit the cliff. Note this removes one way to exceed the cap — it
				// does not make the cap an invariant, since Evict tolerates a failed delete (see its
				// comment); the cap is a bound on growth, not a guarantee about the directory.
				if (payload.Length > maxBytes)
				{
					LogDiagnostic($"Shadow cache entry {key} is {payload.Length} bytes, over the {maxBytes} byte cap; not stored.");
					return;
				}

				Directory.CreateDirectory(dir);
				Evict(dir, maxBytes - payload.Length, key);

				// Write to a unique temp name and move into place, so a crash or a second process
				// mid-write cannot leave a torn file under the real key.
				var path = PathForKey(dir, key);
				temp = path + "." + Guid.NewGuid().ToString("N") + TempSuffix;

				using (var file = new FileStream(temp, FileMode.Create, FileAccess.Write, FileShare.None))
				using (var writer = new BinaryWriter(file))
				{
					writer.Write(Magic);
					writer.Write(HeaderVersion);
					writer.Write(key);
					writer.Write((long)payload.Length);
					writer.Write(payload);
					writer.Flush();

					// Flush to the disk, not just to the page cache. Without this the rename can
					// become durable while the payload has not, leaving a file of exactly the right
					// length whose tail is zeros after an OS crash — which passes the length check
					// and yields a wrong shadow layer, and a wrong shadow layer is a desync. Costs
					// nothing on the read path, and is noise next to generating the payload.
					file.Flush(true);
				}

				File.Move(temp, path, true);
				temp = null;
			}
			catch (Exception e)
			{
				LogDiagnostic($"Could not write shadow cache entry {key}: {e.Message}");

				if (temp != null)
				{
					try { File.Delete(temp); }
					catch (Exception) { }
				}
			}
		}

		// This type must never disturb its caller, and Log.Write on an unregistered channel kills the
		// process from the logging thread where no catch can reach it.
		static void LogDiagnostic(string message)
		{
			if (Log.ChannelExists("debug"))
				Log.Write("debug", message);
		}

		/// <summary>Payload length, or -1 if this file is not a valid entry for <paramref name="key"/>.</summary>
		static long ReadAndValidateHeader(Stream s, string key)
		{
			var reader = new BinaryReader(s, Encoding.UTF8, true);

			if (reader.ReadUInt32() != Magic)
				return -1;

			if (reader.ReadInt32() != HeaderVersion)
				return -1;

			// The key is in the filename already; repeating it inside guards against a truncated or
			// relocated file being served for the wrong map.
			if (reader.ReadString() != key)
				return -1;

			var payloadLength = reader.ReadInt64();
			return payloadLength < 0 ? -1 : payloadLength;
		}

		/// <summary>
		/// Delete least-recently-used entries until the directory fits in <paramref name="budget"/>.
		/// </summary>
		static void Evict(string cacheDir, long budget, string incoming)
		{
			var dir = new DirectoryInfo(cacheDir);
			if (!dir.Exists)
				return;

			// A process killed mid-write leaves its temp behind. Nothing else would ever remove it,
			// and it is invisible to the *.bin accounting below, so orphans would silently eat the
			// cap. Only reap ones old enough that they cannot belong to a write still in flight.
			foreach (var orphan in dir.GetFiles("*" + TempSuffix))
			{
				if (DateTime.UtcNow - orphan.LastWriteTimeUtc < StaleTempAge)
					continue;

				try { orphan.Delete(); }
				catch (Exception) { }
			}

			var files = dir.GetFiles("*.bin");
			var total = files.Sum(f => f.Length);
			if (total <= budget)
				return;

			foreach (var f in files.OrderBy(f => f.LastWriteTimeUtc))
			{
				if (total <= budget)
					break;

				var candidate = Path.GetFileNameWithoutExtension(f.Name);
				if (candidate == incoming)
					continue;

				lock (SyncRoot)
					if (InUse.Contains(candidate))
						continue;

				try
				{
					var size = f.Length;
					f.Delete();
					total -= size;
				}
				catch (Exception)
				{
					// Locked by another process (Windows) or already gone. Leave it; the cap is a
					// bound on growth, not an invariant worth failing a map load over.
				}
			}
		}

		static string PathForKey(string dir, string key)
		{
			return Path.Combine(dir, key + ".bin");
		}
	}
}
