#region Copyright & License Information
/*
 * Copyright (c) The OpenRA Developers and Contributors
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

/*
 * THE ARTEFACT. At the outer boundary of a nuclear scar -- River Zeta's shoreline, reported
 * 2026-09-19 -- the cells read blocky: bright ground hard against dark, along square axis-aligned
 * edges. That is NOT the fade metric, which was made Euclidean in 1e952767 and is not revisited
 * here. It is that a smudge is ONE FLAT ALPHA OVER A WHOLE CELL, so at partial coverage the CELL is
 * the smallest thing that can change. Dimming cannot reach below it.
 *
 * And there was very little dimming to see in the first place: with ShoreFadeCells 2 and
 * ShoreFadeMinAlpha 0.7 the entire ramp spans alpha 0.800 to 1.0. Measured offline over
 * demo-nuke-river-zeta's 21-cell shoreline (tools/impact-scar/scar_edge_preview.py), mean cell
 * luminance by distance to the water read 43.7 / 43.4 / 43.6 / 43.3 / 44.4 -- flat to within one
 * luminance point across the whole boundary. That flatness IS the defect, counted.
 *
 * THE FIX IS FEWER PIXELS, NOT FAINTER ONES. Each band gets two sparser cuts of its own art, at 50%
 * and 25% of its coverage, generated by gen_scars.py as nested subsets of the same noise field.
 * SmudgeLayer picks a cut using the shore-fade value it already computes. Same window, same
 * measurement: 48.4 / 46.6 / 46.8 / 43.3 / 44.4 -- a gradient over two cells.
 *
 * WHY THE FADE IS KEPT AND NOT REPLACED. A boundary cell gets the sparser sprite AND the ramped
 * alpha, so ShoreFadeMinAlpha still means exactly what its own [Desc] says it means. The two levers
 * act on different things: alpha on the whole cell, the cut on how much of it is drawn at all.
 *
 * WHY NEIGHBOUR COUNTING IS NOT USED, since it is the obvious alternative and it does not work here.
 * The five bands are ANNULI living in five separate SmudgeLayers, each with its own tile dictionary.
 * A cell's neighbour in the next band out is not in this layer's dictionary at all, so "how many of
 * my 8 neighbours are scarred" would answer 0 for the whole outer ring of EVERY band and classify
 * the entire disc as boundary. The shore-fade value already answers the question that was actually
 * asked -- how close is this cell to ground this layer cannot draw on.
 *
 * WHAT THIS FIXTURE CANNOT SEE. It pins the wiring, the art and the reachability of every tier. It
 * cannot see whether the result looks like a dissolve; that is the offline preview's job and then a
 * screenshot's.
 */

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using NUnit.Framework;
using OpenRA.Mods.Common.Traits;

namespace OpenRA.Test
{
	[TestFixture]
	public class ScarEdgeVariantTest
	{
		/// <summary>The five smudge types that make up a nuclear scar.</summary>
		static readonly string[] ScarTypes = { "ScarCore", "ScarCrater", "ScarChar", "ScarBurn", "ScarRim" };

		/// <summary>Tileset extensions the art must exist for. INTERIOR is absent on purpose: the
		/// sequences carry `TilesetOverrides: INTERIOR: TEMPERAT`, so interior maps read the .tem files.</summary>
		static readonly string[] TilesetExtensions = { "tem", "sno", "des" };

		// ---- 1. the opt-in ---------------------------------------------------------------------

		[Test]
		public void TheCodeDefaultIsTheBaselineLook()
		{
			var info = new SmudgeLayerInfo();
			Assert.That(info.EdgeSequences, Is.Empty,
				"EdgeSequences now has a default, so every smudge layer in every mod silently starts " +
				"swapping art at boundaries. It must be opted in per layer.");
			Assert.That(info.EdgeAlphaThresholds, Is.Empty);
		}

		[Test]
		public void EveryScarBandNamesTwoCutsAndTwoThresholds()
		{
			foreach (var type in ScarTypes)
			{
				var layer = ScarLayer(type);
				Assert.That(Cuts(layer), Has.Length.EqualTo(2),
					$"{type} no longer names two edge cuts. With none it reverts to one flat sprite per " +
					"cell at the waterline, which is the blocky boundary this exists to remove; with one " +
					"the gradient is a single step rather than the two the offline preview was judged on.");

				Assert.That(Thresholds(layer), Has.Length.EqualTo(2),
					$"{type}'s EdgeAlphaThresholds no longer has two entries. The two lists are read in " +
					"lockstep and SmudgeLayer throws at map load if they differ -- so this fails the mod, " +
					"not just the look.");
			}
		}

		[Test]
		public void TheStockSmudgeLayersAreLeftAlone()
		{
			// Same boundary the other two scar fixtures draw. Scorch and Crater are the RA smudge types
			// every ordinary weapon in the mod shares, and every one of them would start swapping art at
			// a shoreline.
			foreach (var type in new[] { "Scorch", "Crater" })
			{
				Assert.That(Cuts(ScarLayer(type)), Is.Empty,
					$"the stock {type} layer has been given edge cuts. That widens a decision made about " +
					"nuclear scarring onto conventional craters. Deliberate? Say so in the commit message.");
			}
		}

		// ---- 2. the wiring the lint cannot check -----------------------------------------------

		[Test]
		public void EveryNamedCutExistsAndIsWiredToArtOnDisk()
		{
			// THE REASON THIS FIXTURE EXISTS AT ALL. SmudgeLayerInfo.Sequence carries no
			// [SequenceReference] (there is nowhere to hang one: the sequence GROUP is the field and the
			// variants are the sequences, which is inverted from every other consumer), and EdgeSequences
			// inherits that. So a typo in a group name is not a lint error, not a build error and not a
			// warning -- it is an IndexOutOfRangeException at map load, or worse, a group that silently
			// resolves to nothing. This walks world.yaml -> sequences-misc.yaml -> the files.
			var groups = SequenceGroups();

			foreach (var type in ScarTypes)
			{
				foreach (var cut in Cuts(ScarLayer(type)))
				{
					Assert.That(groups.ContainsKey(cut), Is.True,
						$"{type} names edge sequence '{cut}', which sequences-misc.yaml does not define. " +
						"This is not caught by --check-yaml or --check-missing-sprites; it surfaces at map " +
						"load as an exception with no mention of the name.");

					Assert.That(groups[cut], Is.Not.Empty, $"'{cut}' defines no variants");

					foreach (var sprite in groups[cut])
						foreach (var ext in TilesetExtensions)
						{
							var path = Path.Combine(ScarArtDirectory(), $"{sprite}.{ext}");
							Assert.That(File.Exists(path), Is.True,
								$"'{cut}' names sprite {sprite} but {sprite}.{ext} is missing from " +
								"bits/misc/scars. Regenerate with tools/impact-scar/gen_scars.py and copy " +
								"out/ over that directory.");
						}
				}
			}
		}

		[Test]
		public void EveryCutHasTheSameVariantCountAsItsBand()
		{
			// The ordinal contract. A cell keeps its variant's POSITION when it switches tier, because
			// the cuts are nested subsets of one noise field per (band, variant, depth) -- so variant 3's
			// 25% cut is literally a subset of variant 3's pixels and the cell thins rather than
			// reshuffling. SmudgeLayer throws at load if the counts differ; this says so earlier and with
			// the band named.
			var groups = SequenceGroups();

			foreach (var type in ScarTypes)
			{
				var layer = ScarLayer(type);
				var baseGroup = NodeValue(layer, "Sequence");
				Assert.That(groups.ContainsKey(baseGroup), Is.True, $"{type}'s Sequence '{baseGroup}' is not defined");

				foreach (var cut in Cuts(layer))
					Assert.That(groups[cut].Count, Is.EqualTo(groups[baseGroup].Count),
						$"'{cut}' holds {groups[cut].Count} variants against '{baseGroup}'s {groups[baseGroup].Count}. " +
						"SmudgeLayer selects a cut by ordinal and refuses to load a mismatch.");
			}
		}

		// ---- 3. the thresholds actually select something ---------------------------------------

		[Test]
		public void EveryTierIsReachableFromTheShoreFadeThisLayerConfigures()
		{
			// THE ACCEPTANCE BAR, and the failure it guards is entirely silent. The tiers are selected by
			// the shore-fade alpha, whose reachable values are fixed by ShoreFadeCells and
			// ShoreFadeMinAlpha: at 2 and 0.7 they are 0.800, 0.841, 0.900, 0.924, 0.983 and 1.0, so a
			// threshold at 0.75 selects NOTHING and a second threshold at 0.805 selects nothing the first
			// did not already take. Either way the mod loads, the art ships, and the boundary looks
			// exactly as it did before.
			foreach (var type in ScarTypes)
			{
				var layer = ScarLayer(type);
				var fadeCells = int.Parse(NodeValue(layer, "ShoreFadeCells"), CultureInfo.InvariantCulture);
				var minAlpha = float.Parse(NodeValue(layer, "ShoreFadeMinAlpha"), CultureInfo.InvariantCulture);
				var thresholds = Thresholds(layer);

				for (var i = 1; i < thresholds.Length; i++)
					Assert.That(thresholds[i], Is.GreaterThan(thresholds[i - 1]),
						$"{type}'s EdgeAlphaThresholds do not ascend. The first tier a cell does not exceed " +
						"wins, so an out-of-order entry makes the later tier unreachable rather than wrong.");

				// One boundary cell at the origin, every cell the fade can see from it.
				//
				// THE ORIGIN ITSELF IS EXCLUDED, and leaving it in makes this test vacuous. A boundary
				// cell scores minAlpha exactly -- 0.7 -- which is BELOW every threshold, so it selects
				// tier 0 on its own and the assertion passes whatever the thresholds are. It is also a
				// cell that never carries a smudge: LeaveSmudgeWarhead refused it, which is why
				// ShoreAlphaAt's own summary calls that return value one that never matters in practice.
				// Confirmed: with the origin included, a threshold of 0.75 -- unreachable by any cell
				// that can actually draw -- passed this test.
				var alphas = new List<float>();
				for (var dy = -fadeCells; dy <= fadeCells; dy++)
					for (var dx = -fadeCells; dx <= fadeCells; dx++)
						if (dx != 0 || dy != 0)
							alphas.Add(SmudgeLayer.ShoreAlphaAt(new CPos(dx, dy), fadeCells, minAlpha,
								c => c.X == 0 && c.Y == 0));

				for (var i = 0; i < thresholds.Length; i++)
				{
					var i1 = i;
					var selects = alphas.Any(a => Tier(a, thresholds) == i1);
					Assert.That(selects, Is.True,
						$"{type}'s tier {i} (threshold {thresholds[i].ToString(CultureInfo.InvariantCulture)}) is " +
						$"never selected by any cell. With ShoreFadeCells {fadeCells} and ShoreFadeMinAlpha " +
						$"{minAlpha.ToString(CultureInfo.InvariantCulture)} the reachable " +
						$"alphas are {string.Join(", ", alphas.Distinct().OrderBy(a => a).Select(a => a.ToString("0.000", CultureInfo.InvariantCulture)))}. " +
						"The cut ships and is never drawn, and nothing anywhere reports it.");
				}

				// And the band's own art must survive somewhere, or the whole disc is drawn from cuts.
				Assert.That(alphas.Any(a => Tier(a, thresholds) == -1), Is.True,
					$"{type}'s thresholds select a cut for EVERY cell the fade reaches, so the band's own " +
					"art never draws within range of a boundary. Lower the last threshold.");
			}
		}

		/// <summary>SmudgeLayer.EdgeSequenceFor's choice, as an index, or -1 for the band's own art.</summary>
		static int Tier(float alpha, float[] thresholds)
		{
			for (var i = 0; i < thresholds.Length; i++)
				if (alpha <= thresholds[i])
					return i;

			return -1;
		}

		// ---- reading the mod -------------------------------------------------------------------

		static string[] Cuts(MiniYaml layer)
		{
			var value = NodeValue(layer, "EdgeSequences");
			if (string.IsNullOrEmpty(value))
				return Array.Empty<string>();

			return value.Split(',').Select(v => v.Trim()).Where(v => v.Length > 0).ToArray();
		}

		static float[] Thresholds(MiniYaml layer)
		{
			var value = NodeValue(layer, "EdgeAlphaThresholds");
			if (string.IsNullOrEmpty(value))
				return Array.Empty<float>();

			return value.Split(',').Select(v => float.Parse(v.Trim(), CultureInfo.InvariantCulture)).ToArray();
		}

		/// <summary>The SmudgeLayer block in world.yaml whose Type is this smudge type.</summary>
		static MiniYaml ScarLayer(string type)
		{
			var world = MiniYaml.FromFile(FindMod("rules", "world.yaml")).First(n => n.Key == "World");
			var layer = world.Value.Nodes
				.Where(n => n.Key.StartsWith("SmudgeLayer", StringComparison.Ordinal))
				.FirstOrDefault(n => NodeValue(n.Value, "Type") == type);

			Assert.That(layer, Is.Not.Null, $"world.yaml no longer declares a {type} smudge layer");
			return layer.Value;
		}

		/// <summary>Sequence group name -> the sprite names it lists. Only the scarband groups, since
		/// nothing else in that file is shaped like this.</summary>
		static Dictionary<string, List<string>> SequenceGroups()
		{
			var groups = new Dictionary<string, List<string>>();
			foreach (var node in MiniYaml.FromFile(FindMod("sequences", "sequences-misc.yaml")))
			{
				if (!node.Key.StartsWith("scarband", StringComparison.Ordinal))
					continue;

				groups[node.Key] = node.Value.Nodes
					.Where(n => n.Key != "Defaults")
					.Select(n => n.Value.Value?.Trim() ?? n.Key)
					.ToList();
			}

			Assert.That(groups, Is.Not.Empty,
				"no scarband sequence groups parsed out of sequences-misc.yaml -- this test is no longer " +
				"reading what it claims to, rather than the mod having lost its scar art.");

			return groups;
		}

		static string ScarArtDirectory()
		{
			return FindMod("bits", "misc", "scars", "bza1.tem") is var probe && probe != null
				? Path.GetDirectoryName(probe)
				: throw new DirectoryNotFoundException("mods/ww3mod/bits/misc/scars");
		}

		static string NodeValue(MiniYaml node, string key)
		{
			return node.Nodes.FirstOrDefault(n => n.Key == key)?.Value.Value?.Trim();
		}

		static string FindMod(params string[] parts)
		{
			var dir = new DirectoryInfo(AppContext.BaseDirectory);
			for (var i = 0; i < 10 && dir != null; i++, dir = dir.Parent)
			{
				var candidate = Path.Combine(new[] { dir.FullName, "mods", "ww3mod" }.Concat(parts).ToArray());
				if (File.Exists(candidate))
					return candidate;
			}

			throw new FileNotFoundException($"could not locate mods/ww3mod/{string.Join("/", parts)}");
		}
	}
}
