#region Copyright & License Information
/*
 * Copyright (c) The OpenRA Developers and Contributors
 * This file is part of OpenRA, which is free software. It is made
 * available to you under the terms of the GNU General Public License
 * as published by the Free Software Foundation, either version 3 of
 * the License, or (at your option) any later version. For more
 * information, see COPYING.
 */
#endregion

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;
using OpenRA.Primitives;

namespace OpenRA.Test
{
	/// <summary>
	/// Map.SetShadowLayer fills the layer with Parallel.ForEach over from-cells. That is only sound
	/// because each from-cell owns a disjoint slot range, so scheduling cannot change the result.
	///
	/// <para>These tests attack the claim at the store: they fill the same layer serially and
	/// concurrently through the annulus enumeration the map loader uses, and compare every ordered
	/// pair. A write that leaked outside its from-cell's range — the failure the disjointness claim
	/// rules out — would show up here as a differing pair, and a torn (byte, byte) write would show
	/// up as a value that was never assigned to anything.</para>
	///
	/// <para>What this does NOT cover is the purity of Map.RecomputeShadowFrom's own reads; that is
	/// verified against a real map by regenerating river-zeta-ww3 and comparing the bytes to the
	/// cache generated by the previous serial implementation.</para>
	/// </summary>
	[TestFixture]
	public class MapShadowLayerParallelismTest
	{
		// Wider than the 65-cell annulus diameter in both axes, so interior from-cells carry a full
		// unclipped annulus and edge cells carry a clipped one. Deliberately smaller than a shipped
		// map: this fixture is about scheduling, and comparing every pair on a 98x82 footprint costs
		// minutes without testing anything the smaller footprint misses.
		const int Width = 70;
		const int Height = 70;

		const MapGridType Grid = MapGridType.Rectangular;

		static IEnumerable<MPos> AllCells()
		{
			for (var v = 0; v < Height; v++)
				for (var u = 0; u < Width; u++)
					yield return new MPos(u, v);
		}

		static IEnumerable<MPos> Annulus(MPos from)
		{
			for (var dv = -MapShadowLayer.MaxRange; dv <= MapShadowLayer.MaxRange; dv++)
			{
				for (var du = -MapShadowLayer.MaxRange; du <= MapShadowLayer.MaxRange; du++)
				{
					var distance = Exts.ISqrt((du * du) + (dv * dv), Exts.ISqrtRoundMode.Ceiling);
					if (distance < MapShadowLayer.MinRange || distance > MapShadowLayer.MaxRange)
						continue;

					var to = new MPos(from.U + du, from.V + dv);
					if (to.U >= 0 && to.U < Width && to.V >= 0 && to.V < Height)
						yield return to;
				}
			}
		}

		// Never (0, 0), so an unwritten pair is distinguishable from a written one.
		static (byte GroundShadow, byte AirborneShadow) Value(MPos from, MPos to)
		{
			var f = (from.V * Width) + from.U;
			var t = (to.V * Width) + to.U;
			return ((byte)(1 + (((f * 31) + (t * 17)) % 255)), (byte)(1 + (((f * 7) + (t * 13)) % 255)));
		}

		static void Fill(MapShadowLayer layer, MPos from)
		{
			foreach (var to in Annulus(from))
				layer[from, to] = Value(from, to);
		}

		[Test(Description = "Filling per from-cell concurrently gives bit-identical entries to filling serially.")]
		public void ParallelFillMatchesSerialFill()
		{
			var serial = new MapShadowLayer(Grid, new Size(Width, Height));
			foreach (var from in AllCells())
				Fill(serial, from);

			var parallel = new MapShadowLayer(Grid, new Size(Width, Height));
			Parallel.ForEach(AllCells(), from => Fill(parallel, from));

			// Every slot in the layer belongs to some from-cell's annulus, so a write that escaped
			// its own from-cell's range necessarily lands in another from-cell's annulus and is
			// caught here. That is why comparing the annulus is sufficient, not merely cheaper.
			var compared = 0;
			foreach (var from in AllCells())
			{
				foreach (var to in Annulus(from))
				{
					if (serial[from, to] != parallel[from, to])
						Assert.Fail($"Pair {from} -> {to} differs: serial {serial[from, to]}, parallel {parallel[from, to]}.");

					// Value is never (0, 0), so this also catches a write that was lost entirely.
					Assert.That(parallel[from, to], Is.EqualTo(Value(from, to)));
					compared++;
				}
			}

			// Guard against the whole comparison being vacuous.
			Assert.That(compared, Is.GreaterThan(1_000_000));
		}

		[Test(Description = "Concurrent fill leaves pairs outside the annulus untouched.")]
		public void ParallelFillWritesNothingOutsideTheAnnulus()
		{
			var layer = new MapShadowLayer(Grid, new Size(Width, Height));
			Parallel.ForEach(AllCells(), from => Fill(layer, from));

			// A few representative from-cells rather than all of them: one interior, one on each
			// edge, one corner. Checking every from-cell against every to-cell is quadratic and
			// adds no case this does not already cover.
			var probes = new[]
			{
				new MPos(Width / 2, Height / 2), new MPos(0, 0),
				new MPos(Width - 1, Height - 1), new MPos(0, Height / 2), new MPos(Width / 2, 0)
			};

			var checkedPairs = 0;
			foreach (var from in probes)
			{
				var expected = Annulus(from).ToHashSet();
				foreach (var to in AllCells())
				{
					if (expected.Contains(to))
						continue;

					Assert.That(layer[from, to], Is.EqualTo(default((byte, byte))),
						$"Pair {from} -> {to} was written but is outside the annulus.");
					checkedPairs++;
				}
			}

			Assert.That(checkedPairs, Is.GreaterThan(0));
		}
	}
}
