#!/usr/bin/env python3
"""Tunguska 30mm guns vs a named target: hit rate, kill rate, rounds-per-kill.

Answers "can the Tunguska's guns kill what they are shooting at, and how many can
they kill on one 180-round load?" by replicating the shipped engine pipeline
rather than approximating it. No game launch; arithmetic over the resolved rules.

Targets (--target): littlebird | rifleman | humvee.
The weapon follows the target: `30mm.Tunguska.AA` for the helicopter,
`30mm.Tunguska.AG` for the two ground profiles. Their warhead sets DIFFER, and
this script reads both out of tools/combat-sim/data/stats.json rather than
hardcoding them, because warheads filter on target type.

ENGINE PATHS REPLICATED (verified 260822, engine @ 84328dcc)

  Bullet.cs:200-222     target = args.PassiveTarget, then
                        target += WVec.FromPDF(rng,2) * maxInaccuracyOffset / 1024
  Bullet.cs:213         the InaccuracyPerProjectile branch is gated on
                        `lastPosIsSet`, which is `readonly bool = false` and is
                        never assigned (Bullet.cs:170). The branch is DEAD, so
                        ^30mm.Tunguska's `InaccuracyPerProjectile: 12,12,0` has
                        no effect and every round scatters independently about
                        the target centre.
  Util.cs:406-408       InaccuracyType.Maximum -> inaccuracy * dist / weaponMaxRange,
                        so scatter grows linearly with range and is FULL 1c0 only
                        at 18c0.
  WDist.cs:56-60        FromPDF(r,2) = (r.Next(-1024,1024)+r.Next(-1024,1024))/2,
                        int division truncating toward zero. Triangular per axis,
                        X and Y independent in WORLD axes (so the cloud is
                        square-cornered, not radial), Z always 0.
  TargetDamageWarhead   lands iff DistanceFromEdge <= Spread. Spread is UNSET in
  .cs:23,71-97          YAML so it is the default WDist(1) -- effectively "inside
                        the hitshape". Damage is then scaled by
                        CenterProximityPercent, and ONLY here by
                        RangeDamageMultiplier.
  Circle.cs:53-57       CenterProximityPercent = 100*(Radius-|v|)/Radius. A hit on
                        the rim does ZERO damage; only a centre hit does full.
  Rectangle.cs:117-127  DistanceFromEdge is computed in the actor's LOCAL frame,
                        so whether a round lands depends on facing; but
                        CenterProximityPercent normalises against the
                        half-DIAGONAL of an unrotated |v|, so the damage scale
                        does not. Humvee half-diagonal = |(235,500)| = 552.
  DamageWarhead.cs:     RangeDamageMultiplier lerps 100 -> DamageAtMaxRange over
  111-119               the weapon's range.
  DamageWarhead.cs:     ArmorDirectionPercent -- {Front,Side,Rear,Top,Bottom}
  121-197               percentages of Thickness, selected by the yaw between
                        victim and impact. Ported branch-for-branch below.
                        Applies only when Distribution has exactly 5 entries.
  DamageWarhead.cs:     if Penetration < Thickness: damage = damage*pen/thickness.
  216-231               Skipped entirely when Thickness == 0 (infantry).
  SpreadDamageWarhead   effectiveRange[i] = i*Spread -> [0,64,128,192,256];
  .cs:25,52,134-141     Falloff [100,37,14,5,0] lerped between those steps,
                        measured from the hitshape EDGE.

CORRECTION 260822 -- SpreadDamage's DamageAtMaxRange is DEAD CODE.
`RangeDamageMultiplier` is called from exactly one place in the engine,
TargetDamageWarhead.cs:88-89. SpreadDamageWarhead never calls it, so the
`DamageAtMaxRange: 50` on ^30mm's Warhead@Spread has no effect and its damage is
flat with range. A previous revision of this script applied the range lerp to the
spread warhead too, which under-counted long-range damage. Fixed here.

THE TRAP THIS SCRIPT AVOIDS: P(hit) != P(kill). humvee-hitshape-ladder.py's
docstring was corrected on 260821 for assuming a landed round is a kill. Here a
landed round is USUALLY NOT a kill, because CenterProximityPercent throws away
almost all of the damage for anything but a dead-centre impact. This script
therefore accumulates damage per round and reports rounds-to-kill, never a bare
hit rate presented as lethality.

TARGET DATA, resolved from tools/combat-sim/data/stats.json (dump-stats.sh
@ 84328dcc) and the live hitshape YAML. Not regenerated by this script.
  littlebird  hp 300,  Armor Light t5,  no distribution, 265 u/tick,
              HitShape Circle r32          (aircraft.yaml:64-66)
              TargetTypes: Air, AirDetonateAttack, Helicopter
                                           (aircraft.yaml:38, 173)
  rifleman    actor `e3` "Rifleman" -- the representative rifle infantryman;
              `e1` Conscript and `ar` Automatic Rifleman are byte-identical on
              every field this model reads (hp 200, Armor Kevlar t0, 25 u/tick),
              so the choice does not move a number.
              HitShape@Standing Circle r30 (infantry.yaml:147-150; the prone
              HitShape@Cover r20 is NOT modelled -- see ASSUMPTIONS).
              TargetTypes: Ground, Infantry, Disguise  (infantry.yaml:63)
  humvee      hp 4000, Armor Light t10, distribution 100,80,80,80,60,
              150 u/tick, HitShape Rectangle TopLeft -235,-500 /
              BottomRight 235,500  (vehicles-america.yaml:55-73)
              TargetTypes: Ground, Vehicle, Light  (vehicles-america.yaml:62)

ASSUMPTIONS, stated so they can be attacked
  - The gun is modelled alone. The 9M311 missile is excluded deliberately: the
    question is what the GUNS do. Note the 180-round pool is SHARED between the
    AA and AG armaments (vehicles-russia.yaml:869-873), so "kills per load" is a
    combined budget, not one budget each.
  - "moving" gives the target a constant-heading run at its full speed. That is
    the worst case, not the average -- a target that stops to shoot back is the
    stationary row. Real engagements sit between the two. For ground profiles the
    heading is tied to the facing (vehicles drive where they point); for the
    helicopter it is independent, preserving the original model.
  - No lead prediction, because Bullet.cs:200 aims at PassiveTarget and never
    solves for intercept. Verified by reading, not assumed.
  - Infantry are modelled STANDING (r30). Prone infantry (r20) are ~2.2x harder
    to land a TargetDamage on and take less SpreadDamage; the rifleman rows are
    therefore an upper bound on the AG gun's anti-infantry performance.
  - Damage modifiers outside the warhead (veterancy, FirepowerMultiplier) are
    not applied; a stock-veterancy Tunguska is assumed.
  - Terrain, cover, garrisoning and en-route blocking are not modelled.
"""
import argparse
import json
import math
import os
import random

STATS = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     "..", "data", "stats.json")

TICKS_PER_SECOND = 60 / 3.6  # Timestep: 60 -> 16.67 tps
AMMO = 180                   # AmmoPool@1, vehicles-russia.yaml:872 (shared pool)


# --------------------------------------------------------------------------
# Target profiles
# --------------------------------------------------------------------------

class Profile:
    def __init__(self, name, weapon, hp, thickness, distribution, speed,
                 shape, target_types, heading_follows_facing):
        self.name = name
        self.weapon = weapon
        self.hp = hp
        self.thickness = thickness
        self.distribution = distribution
        self.speed = speed
        self.shape = shape
        self.target_types = set(target_types)
        self.heading_follows_facing = heading_follows_facing


class Circle:
    """HitShape Circle. Facing-independent in both landing and damage scale."""
    kind = "circle"

    def __init__(self, radius):
        self.radius = radius

    def describe(self):
        return f"Circle r{self.radius}"

    def distance_from_edge(self, dx, dy, facing):
        return max(0, int(math.hypot(dx, dy)) - self.radius)

    def center_proximity_percent(self, dx, dy, facing):
        # Circle.cs:53-57 -- int division.
        return 100 * (self.radius - int(math.hypot(dx, dy))) // self.radius


class Rectangle:
    """HitShape Rectangle, TopLeft/BottomRight symmetric about the origin.

    Landing depends on facing (the offset is rotated into the local frame,
    Rectangle.cs:129-140); the damage scale does not, because
    CenterProximityPercent normalises an unrotated length against the
    half-diagonal (Rectangle.cs:117-127).
    """
    kind = "rect"

    def __init__(self, half_x, half_y):
        self.half_x = half_x
        self.half_y = half_y
        self.half_diagonal = int(math.hypot(half_x, half_y))

    def describe(self):
        return f"Rect {2*self.half_x}x{2*self.half_y} (half-diag {self.half_diagonal})"

    def distance_from_edge(self, dx, dy, facing):
        a = 2 * math.pi * facing / 256.0
        ca, sa = math.cos(a), math.sin(a)
        lx = dx * ca + dy * sa
        ly = -dx * sa + dy * ca
        rx = max(abs(lx) - self.half_x, 0.0)
        ry = max(abs(ly) - self.half_y, 0.0)
        return int(math.hypot(rx, ry))

    def center_proximity_percent(self, dx, dy, facing):
        return 100 * (self.half_diagonal - int(math.hypot(dx, dy))) // self.half_diagonal


PROFILES = {
    "littlebird": Profile(
        name="Littlebird", weapon="30mm.tunguska.aa",
        hp=300, thickness=5, distribution=[], speed=265,
        shape=Circle(32),
        target_types=["Air", "AirDetonateAttack", "Helicopter"],
        heading_follows_facing=False),
    "rifleman": Profile(
        name="Rifleman (e3, standing)", weapon="30mm.tunguska.ag",
        hp=200, thickness=0, distribution=[], speed=25,
        shape=Circle(30),
        target_types=["Ground", "Infantry", "Disguise"],
        heading_follows_facing=True),
    "humvee": Profile(
        name="Humvee", weapon="30mm.tunguska.ag",
        hp=4000, thickness=10, distribution=[100, 80, 80, 80, 60], speed=150,
        shape=Rectangle(235, 500),
        target_types=["Ground", "Vehicle", "Light"],
        heading_follows_facing=True),
}


# --------------------------------------------------------------------------
# Engine ports
# --------------------------------------------------------------------------

def pdf2(rng):
    """WDist.FromPDF(r, 2); C# int division truncates toward zero."""
    s = rng.randrange(-1024, 1024) + rng.randrange(-1024, 1024)
    return int(s / 2)


def range_multiplier(dist, weapon_range, damage_at_max_range):
    """DamageWarhead.RangeDamageMultiplier -- lerp 100 -> DamageAtMaxRange.

    Called ONLY by TargetDamageWarhead (TargetDamageWarhead.cs:88-89).
    """
    of_max = dist / weapon_range
    return int((1 - of_max) * 100 + of_max * damage_at_max_range)


def armor_direction_percent(distribution, alignment):
    """DamageWarhead.ArmorDirectionPercent, ported branch-for-branch.

    `alignment` is (victimYaw - projectileYaw) in WAngle units, 0..1023.
    Not applied for TopAttack/BottomAttack weapons -- neither Tunguska gun is.
    """
    if len(distribution) != 5:
        return 100

    def wangle(a):
        a %= 1024
        return a + 1024 if a < 0 else a

    front_alignment = wangle(alignment + 512)
    rear_alignment = wangle(alignment)
    left_alignment = wangle(alignment - 256)
    right_alignment = wangle(alignment + 256)

    front_mod = rear_mod = left_mod = right_mod = 0.0

    if front_alignment < 256:
        front_mod = (256 - front_alignment) / 256.0
    elif front_alignment > 768:
        front_mod = (front_alignment - 768) / 256.0
    else:
        if rear_alignment < 512:
            rear_mod = (256 - rear_alignment) / 256.0
        else:
            rear_mod = (rear_alignment - 768) / 256.0

    if left_alignment < 256:
        left_mod = (256 - left_alignment) / 256.0
    elif left_alignment > 768:
        left_mod = (left_alignment - 768) / 256.0
    else:
        if right_alignment < 256:
            right_mod = (256 - right_alignment) / 256.0
        elif right_alignment > 256:
            right_mod = (right_alignment - 768) / 256.0

    total = (front_mod * 100.0 * (distribution[0] / 100.0)
             + left_mod * 100.0 * (distribution[1] / 100.0)
             + right_mod * 100.0 * (distribution[1] / 100.0)
             + rear_mod * 100.0 * (distribution[2] / 100.0))
    return int(total)


def apply_armor(damage, penetration, profile, alignment):
    """DamageWarhead.InflictDamage armour step (DamageWarhead.cs:216-231)."""
    thickness = profile.thickness
    if thickness == 0:
        return damage
    thickness = thickness * armor_direction_percent(profile.distribution, alignment) // 100
    if penetration - thickness < 0:
        return damage * penetration // thickness
    return damage


def spread_falloff(distance, spread, falloff):
    """SpreadDamageWarhead.GetDamageFalloff over effectiveRange[i] = i*spread."""
    steps = [i * spread for i in range(len(falloff))]
    inner = steps[0]
    for i in range(1, len(steps)):
        outer = steps[i]
        if outer > distance:
            # int2.Lerp(a, b, mul, div) = a + (b - a) * mul / div, integer.
            return falloff[i - 1] + (falloff[i] - falloff[i - 1]) * (distance - inner) // (outer - inner)
        inner = outer
    return 0


def applies(warhead, profile):
    """Warhead.IsValidAgainst target-type filter."""
    valid = set(warhead.get("valid_targets") or [])
    invalid = set(warhead.get("invalid_targets") or [])
    if invalid & profile.target_types:
        return False
    return bool(valid & profile.target_types)


# --------------------------------------------------------------------------
# Simulation
# --------------------------------------------------------------------------

def load_weapon(key):
    with open(STATS) as fh:
        weapons = json.load(fh)["weapons"]
    if key not in weapons:
        raise SystemExit(f"weapon {key!r} not in {STATS}")
    return weapons[key]


def round_damage(rng, profile, weapon, warheads, dist, inaccuracy, moving,
                 speed_scale=1.0):
    """Damage one round does to the profile. dist = firing range in units."""
    scale = inaccuracy * dist / weapon["range"]          # InaccuracyType.Maximum
    ox = int(pdf2(rng) * scale / 1024)
    oy = int(pdf2(rng) * scale / 1024)

    facing = rng.randrange(256)                # victim facing, uniform
    shooter_bearing = rng.randrange(256)       # firing line, uniform & independent
    alignment = (facing - shooter_bearing) * 4  # WAngle units

    # The target moves during flight; the round was aimed where it used to be.
    # Bullet.cs:227 -- length = Max((target - pos).Length / speed, 1), INTEGER
    # division, so the flight is a whole number of ticks.
    flight_ticks = max(dist // weapon["projectile_speed"], 1)
    if moving:
        heading = (2 * math.pi * facing / 256.0 if profile.heading_follows_facing
                   else rng.uniform(0, 2 * math.pi))
        travel = profile.speed * speed_scale * flight_ticks
        hx = travel * math.cos(heading)
        hy = travel * math.sin(heading)
    else:
        hx = hy = 0.0

    # Offset of the impact point from where the target actually is at impact.
    dx, dy = ox - hx, oy - hy
    edge = profile.shape.distance_from_edge(dx, dy, facing)

    total = 0
    for wh in warheads:
        if not applies(wh, profile):
            continue

        if wh["type"] == "TargetDamageWarhead":
            # Spread is unset in YAML -> default WDist(1).
            spread = wh["spread"] if wh["spread"] is not None else 1
            if edge > spread:
                continue
            modifier = profile.shape.center_proximity_percent(dx, dy, facing)
            if wh["damage_at_max_range"] != 100:
                modifier = modifier * range_multiplier(
                    dist, weapon["range"], wh["damage_at_max_range"]) // 100
            if modifier <= 0:
                continue
            d = apply_armor(wh["damage"], wh["penetration"], profile, alignment)
            total += d * modifier // 100

        elif wh["type"] == "SpreadDamageWarhead":
            fo = spread_falloff(edge, wh["spread"], wh["falloff"])
            if fo <= 0:
                continue
            # NOTE: no RangeDamageMultiplier here -- see CORRECTION in docstring.
            d = apply_armor(wh["damage"], wh["penetration"], profile, alignment)
            total += d * fo // 100

    return total


def simulate(profile, weapon, warheads, dist, inaccuracy, moving, rounds, seed,
             speed_scale=1.0, engagements=1000):
    """Sample `rounds` independent rounds, then derive lethality from them.

    Rounds are i.i.d. -- InaccuracyPerProjectile is dead (see docstring), so
    there is no round-to-round correlation to preserve and firing them in
    sequence buys nothing over sampling them in a batch. Expected rounds-to-kill
    is then HP / E[damage per round] (Wald's identity; the overshoot term is
    negligible at the tens-to-hundreds of rounds seen here).

    `engagements` bootstrap draws from that damage sample give the median and,
    more usefully, P(kill within the 180-round pool) -- which is the number that
    actually answers "can this gun kill a helicopter at all".
    """
    rng = random.Random(seed)
    damages = [round_damage(rng, profile, weapon, warheads, dist, inaccuracy,
                            moving, speed_scale)
               for _ in range(rounds)]

    damaging = sum(1 for d in damages if d > 0)
    mean_dmg = sum(damages) / rounds

    if mean_dmg <= 0:
        return dict(mean_dmg=0.0, mean_rtk=float("inf"), median_rtk=float("inf"),
                    pct_damaging=0.0, kills_per_load=0.0, p_kill_on_load=0.0)

    mean_rtk = profile.hp / mean_dmg

    # Bootstrap the sequential engagement to get the median and P(kill | 180).
    # Skipped when the expected round count is already far past the pool: the
    # answer is 0% and the walk would dominate the runtime.
    if mean_rtk > AMMO * 3:
        return dict(
            mean_dmg=mean_dmg, mean_rtk=mean_rtk, median_rtk=float("inf"),
            pct_damaging=100 * damaging / rounds,
            kills_per_load=AMMO / mean_rtk, p_kill_on_load=0.0)

    boot = []
    killed_on_load = 0
    cap = AMMO * 6
    for _ in range(engagements):
        hp = profile.hp
        n = 0
        while hp > 0 and n < cap:
            hp -= damages[rng.randrange(rounds)]
            n += 1
        if hp <= 0:
            boot.append(n)
            if n <= AMMO:
                killed_on_load += 1
    boot.sort()
    median = boot[len(boot) // 2] if boot else float("inf")

    return dict(
        mean_dmg=mean_dmg,
        mean_rtk=mean_rtk,
        median_rtk=median,
        pct_damaging=100 * damaging / rounds,
        kills_per_load=AMMO / mean_rtk,
        p_kill_on_load=killed_on_load / engagements,
    )


def burst_seconds(weapon, rounds):
    burst = weapon["burst"]
    delay = weapon["burst_delays"][0]
    cycles = rounds / burst
    ticks = cycles * (burst * delay + weapon["burst_wait"])
    return ticks / TICKS_PER_SECOND


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", choices=sorted(PROFILES), default="littlebird")
    ap.add_argument("--rounds", type=int, default=60000,
                    help="independent rounds sampled per cell")
    ap.add_argument("--seed", type=int, default=20260822)
    ap.add_argument("--speed-scale", type=float, default=1.0,
                    help="multiplier on the target's speed in the MOVING rows; "
                         "1.0 = flat out. Use e.g. 0.25 to model a target that "
                         "is manoeuvring rather than transiting.")
    ap.add_argument("--inaccuracies", type=int, nargs="+",
                    default=[1024, 512, 448, 384, 320, 288, 256, 192])
    ap.add_argument("--ranges", type=int, nargs="+", default=None,
                    help="firing ranges in world units; default 4c0/9c0/18c0")
    args = ap.parse_args()

    profile = PROFILES[args.target]
    weapon = load_weapon(profile.weapon)
    warheads = weapon["warheads"]
    applied = [w for w in warheads if applies(w, profile)]
    skipped = [w for w in warheads if not applies(w, profile)]

    ranges = args.ranges or [4608, 9216, 18432]
    min_range = weapon.get("min_range") or 0
    usable = [r for r in ranges if r >= min_range]
    blocked = [r for r in ranges if r < min_range]

    def label(r):
        return f"{r // 1024}c{r % 1024} " + ("close" if r <= 5120 else
                                             "mid" if r <= 12288 else "max")

    print(f"TARGET {profile.name} — {profile.hp} HP, {profile.shape.describe()}, "
          f"Armor t{profile.thickness}"
          + (f" dist {','.join(map(str, profile.distribution))}" if profile.distribution else "")
          + f", {profile.speed} u/tick")
    print(f"WEAPON {profile.weapon} — range {weapon['range']}, MinRange {min_range}, "
          f"Inaccuracy {weapon['inaccuracy']} {weapon['inaccuracy_type']} (shipped), "
          f"burst {weapon['burst']}, pool {AMMO}")
    print("WARHEADS APPLIED: " + ", ".join(
        f"{w['type'].replace('Warhead','')} dmg{w['damage']} pen{w['penetration']} "
        f"[{'/'.join(w['valid_targets'])}]" for w in applied))
    if skipped:
        print("WARHEADS SKIPPED (target-type mismatch): " + ", ".join(
            f"{w['type'].replace('Warhead','')} dmg{w['damage']} "
            f"[{'/'.join(w['valid_targets'])}]" for w in skipped))
    if blocked:
        print(f"RANGES OMITTED (below MinRange {min_range}): "
              + ", ".join(str(r) for r in blocked))
    print(f"{args.rounds} rounds sampled per cell, seed {args.seed}"
          + (f", MOVING rows at {args.speed_scale:g}x speed "
             f"({profile.speed * args.speed_scale:.0f} u/tick)"
             if args.speed_scale != 1.0 else ""))

    for moving in (False, True):
        spd = profile.speed * args.speed_scale
        what = (f"MOVING at {spd:.0f}/tick"
                + (" (full speed — worst case)" if args.speed_scale == 1.0
                   else f" ({args.speed_scale:g}x full speed)")) if moving \
            else "STATIONARY (best case)"
        print(f"\n=== {profile.name} {what} ===")
        print(f"{'Inacc':>6} {'range':>10} {'%rnds':>7} {'dmg':>7} {'rounds':>7} "
              f"{'kills on':>9} {'P(kill':>7} {'time to':>8}")
        print(f"{'':>6} {'':>10} {'w/ dmg':>7} {'/rnd':>7} {'/kill':>7} "
              f"{'180 ld':>9} {'|180)':>7} {'1 kill':>8}")
        for inacc in args.inaccuracies:
            for dist in usable:
                r = simulate(profile, weapon, warheads, dist, inacc, moving,
                             args.rounds, args.seed, args.speed_scale)
                rtk = r["mean_rtk"]
                if rtk == float("inf"):
                    rtk_s, kpl, t_s = "never", "0.00", "never"
                else:
                    rtk_s = f"{rtk:.0f}"
                    kpl = f"{r['kills_per_load']:.2f}"
                    t_s = f"{burst_seconds(weapon, rtk):.1f}s"
                print(f"{inacc:>6} {label(dist):>10} {r['pct_damaging']:>6.2f}% "
                      f"{r['mean_dmg']:>7.2f} {rtk_s:>7} {kpl:>9} "
                      f"{100*r['p_kill_on_load']:>6.1f}% {t_s:>8}")


if __name__ == "__main__":
    main()
